name: bqsp_client
description: Dart client for the BQSP protocol
version: 0.3.2
repository: https://github.com/prty-app/bqsp_client

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
