name: bqsp_client
description: Dart client for the BQSP protocol
version: 0.2.0
repository: https://github.com/prty-app/bqsp_client

environment:
  sdk: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
